title: Bashful Scripting
email: peter@forret.com
author:
  name:   'Peter Forret'
  url:    https://toolstud.io

description: >- # this means to ignore newlines until "baseurl:"
  Getting stuff done with bash
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bash.forret.com"
twitter_username: pforret
github_username:  pforret
highlighter:      rouge
permalink:        pretty

# Build settings

plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - hyde
  - .idea/